const tempData = [
  {
    title: 'Relatos Salvajes',
    year: 2014,
    director: 'Damián Szifron',
    duration: '2:02:00',
    genre: ['Drama', 'Comedia Negra'],
    rate: 4.7,
    poster: '/assets/img/CineAr/Relatos Salvajes.jpg',
    trailer: 'https://www.youtube.com/watch?v=CzJM3jYKjAg',
    sinopsis: 'Seis historias que exploran los límites de la civilización y la barbarie.',
  },
  {
    title: 'El Secreto de sus Ojos',
    year: 2009,
    director: 'Juan José Campanella',
    duration: '2:09:00',
    genre: ['Suspenso', 'Drama'],
    rate: 4.8,
    poster: '/assets/img/CineAr/El_secreto_de_sus_ojos.jpg',
    trailer: 'https://www.youtube.com/watch?v=SOW5EfrTTsE',
    sinopsis: 'Un exagente judicial reabre un caso sin resolver mientras enfrenta sus propios sentimientos.',
  },
  {
    title: 'Nueve Reinas',
    year: 2000,
    director: 'Fabián Bielinsky',
    duration: '1:54:00',
    genre: ['Policial', 'Drama'],
    rate: 4.6,
    poster: '/assets/img/CineAr/Nueve de reinas.jpg',
    trailer: 'https://www.youtube.com/watch?v=I42JYVjQkPI',
    sinopsis: 'Dos estafadores unen fuerzas para dar el golpe de sus vidas.',
  },
  {
    title: 'Esperando la Carroza',
    year: 1986,
    director: 'Alejandro Doria',
    duration: '1:35:00',
    genre: ['Comedia', 'Costumbrismo'],
    rate: 4.9,
    poster: '/assets/img/CineAr/Esperando la carroza.jpg',
    trailer: 'https://www.youtube.com/watch?v=yQY4zGoOqSc',
    sinopsis: 'Una comedia de enredos familiares convertida en clásico de culto argentino.',
  },
];
